version: '2'
services:
    accountapp-app:
        image: accountapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://accountapp-mariadb:3306/accountapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    accountapp-mariadb:
        extends:
            file: mariadb.yml
            service: accountapp-mariadb
